{{ config(materialized='view') }}

SELECT
  STATION_ID,
  DATE_KEY,
  YEAR(DATE_KEY) AS YEAR,
  IFF(MAX_TEMP_TENTHS IS NULL, NULL, MAX_TEMP_TENTHS / 10.0) AS MAX_TEMP_C,
  IFF(MIN_TEMP_TENTHS IS NULL, NULL, MIN_TEMP_TENTHS / 10.0) AS MIN_TEMP_C,
  IFF(PRECIP_TENTHS IS NULL, NULL, PRECIP_TENTHS / 10.0)     AS PRECIP_MM
FROM {{ source('raw', 'WEATHER_DAILY_RAW') }};
