USE DATABASE WEATHER_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE WEATHER_DAILY_RAW (
    STATION_ID      STRING      NOT NULL,
    DATE_KEY        DATE        NOT NULL,
    MAX_TEMP_TENTHS INTEGER,
    MIN_TEMP_TENTHS INTEGER,
    PRECIP_TENTHS   INTEGER,
    LOAD_TS         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME       STRING,
    CONSTRAINT PK_WEATHER_DAILY_RAW PRIMARY KEY (STATION_ID, DATE_KEY)
);

USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE WEATHER_YEARLY_STATS (
    STATION_ID        STRING       NOT NULL,
    YEAR              NUMBER(4,0)  NOT NULL,
    AVG_MAX_TEMP_C    NUMBER(10,2),
    AVG_MIN_TEMP_C    NUMBER(10,2),
    TOTAL_PRECIP_CM   NUMBER(10,2),
    LOAD_TS           TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_WEATHER_YEARLY_STATS PRIMARY KEY (STATION_ID, YEAR)
);
